#!/usr/bin/env node
"use strict";
/** Reproducible, self-contained plugin distributions. Never modifies client settings. */
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { builtinModules } = require("node:module");
const esbuild = require("esbuild");
const pkg = require("../package.json");

const ROOT = path.resolve(__dirname, "..");
const PLUGIN_ID = "agency-agents-router";
const MARKETPLACE_ID = "fooljack-agency";
const TARGETS = ["codex", "claude-code"];
const REPOSITORY = "https://github.com/Fooljack/agency-agents-router-for-pi";
const SCHEMA_ROOT = "https://agent-plugins.org/schemas/1.0.0/";
const json = (value) => JSON.stringify(value, null, 2) + "\n";
const digest = (value) => crypto.createHash("sha256").update(value).digest("hex");
const readText = (file) => fs.readFileSync(path.join(ROOT, file), "utf8").replace(/\r\n/g, "\n");

function dependencyLicenses(metafile) {
  const roots = new Map();
  for (const input of Object.keys(metafile.inputs)) {
    if (!input.replaceAll("\\", "/").includes("node_modules/")) continue;
    let dir = path.dirname(path.resolve(ROOT, input));
    while (dir.startsWith(ROOT + path.sep)) {
      const manifest = path.join(dir, "package.json");
      if (fs.existsSync(manifest)) {
        const info = JSON.parse(fs.readFileSync(manifest, "utf8"));
        if (info.name && info.version) {
          roots.set(dir, info);
          break;
        }
      }
      dir = path.dirname(dir);
    }
  }
  const sections = ["Third-party code included in the standalone MCP runtime.",
    "Generated by npm run build:plugins. Full package licenses follow.\n"];
  const packages = [];
  const sorted = [...roots].sort((a, b) => a[1].name < b[1].name ? -1 : a[1].name > b[1].name ? 1 : 0);
  for (const [dir, info] of sorted) {
    const files = fs.readdirSync(dir).filter((name) => /^(licen[sc]e|copying)(?:[.-].*)?$/i.test(name)
      && fs.statSync(path.join(dir, name)).isFile()).sort();
    if (!files.length) throw new Error(`No license text found for bundled dependency ${info.name}`);
    packages.push({ name: info.name, version: info.version, license: info.license });
    sections.push(`\n${"=".repeat(72)}\n${info.name}@${info.version} (${info.license})\n`);
    for (const file of files) {
      sections.push(`--- ${file} ---\n${fs.readFileSync(path.join(dir, file), "utf8").replace(/\r\n/g, "\n").trim()}\n`);
    }
  }
  return { packages, text: sections.join("\n").trimEnd() + "\n" };
}

function bundledSkill() {
  const skill = readText("integrations/skills/agency-agents-router/SKILL.md");
  const name = /^name: agency-agents-router$/m;
  if (!name.test(skill)) throw new Error("Standalone Skill name changed; review the plugin alias before building.");
  return skill.replace(name, "name: route");
}

function pluginReadme(target) {
  return `# Agency Agents Router — ${target === "codex" ? "Codex" : "Claude Code"}\n\n`
    + `Version: ${pkg.version}. Generated from the shared repository; do not hand-edit this directory.\n\n`
    + "Requires Node.js 20.19+ on the client's PATH (Node 24 LTS recommended). All npm runtime\n"
    + "dependencies and the 279-persona roster are already included. No npm install,\n"
    + "postinstall hook, extra API key, network port or background terminal is needed.\n\n"
    + "Installing/enabling the plugin registers three read-only MCP tools and the route Skill.\n"
    + (target === "claude-code"
      ? "Use `/agency-agents-router:route` followed by your task, or ask Claude to use Agency Agents Router.\n"
      : "Select Agency Agents Router in the plugin/skill picker, or ask Codex to use its route Skill.\n")
    + "The model searches, optionally inspects, then loads one expert's reference instructions.\n"
    + "It still uses the host's own permissions and execution tools; no independent subagent is created.\n\n"
    + `Full installation, update and troubleshooting guide: ${REPOSITORY}/blob/main/docs/${target}.md\n\n`
    + "Avoid enabling both this plugin and the separate standalone MCP/Skill in the same client.\n"
    + "Review and remove only the older router entries if migrating; leave other servers and skills alone.\n\n"
    + "BUNDLE.json lists SHA-256 hashes for the generated files (integrity checks, not a signing certificate).\n"
    + "LICENSE and THIRD_PARTY_NOTICES.md cover the router and roster.\n"
    + "runtime/THIRD_PARTY_LICENSES.txt contains the licenses for the bundled JavaScript dependencies.\n";
}

async function generateArtifacts() {
  const result = await esbuild.build({
    absWorkingDir: ROOT,
    entryPoints: ["mcp-server.js"],
    outfile: path.join(ROOT, ".plugin-build", "mcp-server.cjs"),
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node20.19",
    minify: true,
    sourcemap: false,
    legalComments: "external",
    metafile: true,
    write: false,
    logLevel: "silent",
    charset: "utf8",
  });
  if (result.warnings.length) throw new Error(result.warnings.map((item) => item.text).join("\n"));
  const builtins = new Set(builtinModules.map((name) => name.replace(/^node:/, "")));
  for (const output of Object.values(result.metafile.outputs)) {
    for (const item of output.imports) {
      if (item.external && !builtins.has(item.path.replace(/^node:/, ""))) {
        throw new Error(`Unbundled runtime dependency: ${item.path}`);
      }
    }
  }
  const runtime = result.outputFiles.find((file) => file.path.endsWith("mcp-server.cjs"));
  if (!runtime) throw new Error("esbuild did not produce the MCP runtime");
  const legal = result.outputFiles.find((file) => file.path.endsWith(".LEGAL.txt"));
  const dependencies = dependencyLicenses(result.metafile);
  const roster = fs.readFileSync(path.join(ROOT, "data", "agents.json"));
  const artifacts = new Map();
  const metadata = {
    name: PLUGIN_ID,
    version: pkg.version,
    description: "Search and load 279 specialist personas with an offline, read-only MCP router.",
    author: { name: "Fooljack", url: "https://github.com/Fooljack" },
    homepage: REPOSITORY,
    repository: REPOSITORY,
    license: "MIT",
    keywords: ["agents", "router", "specialists", "mcp"],
  };
  const display = {
    displayName: "Agency Agents Router",
    shortDescription: "279 specialists for coding, research and business tasks",
    longDescription: metadata.description,
    developerName: "Fooljack",
    category: "Productivity",
    capabilities: ["Read"],
    websiteURL: REPOSITORY,
    defaultPrompt: ["为当前任务选择一位领域专家，并按其标准完成工作。"],
  };
  for (const target of TARGETS) {
    const files = new Map();
    const put = (name, value) => files.set(name, Buffer.isBuffer(value) ? value : Buffer.from(value));
    const variable = target === "codex" ? "${PLUGIN_ROOT}" : "${CLAUDE_PLUGIN_ROOT}";
    const server = { type: "stdio", command: "node", args: [`${variable}/runtime/mcp-server.cjs`] };
    put(".mcp.json", json({ mcpServers: { "agency-agents": server } }));
    if (target === "codex") {
      put("plugin.json", json({
        $schema: SCHEMA_ROOT + "plugin.schema.json",
        ...metadata,
        extensions: { "com.openai": { interface: display } },
      }));
      put("mcp.json", json({
        $schema: SCHEMA_ROOT + "mcp.schema.json",
        mcpServers: { "agency-agents": server },
      }));
      // Older Codex versions use the compatibility manifest and .mcp.json.
      put(".codex-plugin/plugin.json", json({
        ...metadata, skills: "./skills/", mcpServers: "./.mcp.json", interface: display,
      }));
    } else {
      // Claude Code discovers skills/ and .mcp.json at their default locations.
      put(".claude-plugin/plugin.json", json(metadata));
    }
    put("skills/route/SKILL.md", bundledSkill());
    put("runtime/mcp-server.cjs", Buffer.from(runtime.contents));
    if (legal) put("runtime/mcp-server.cjs.LEGAL.txt", Buffer.from(legal.contents));
    put("runtime/data/agents.json", roster);
    put("runtime/THIRD_PARTY_LICENSES.txt", dependencies.text);
    put("LICENSE", readText("LICENSE"));
    put("THIRD_PARTY_NOTICES.md", "# Packaged plugin notices\n\n"
      + "Repository paths in the original notices below refer to the shared source tree.\n"
      + "This install keeps the roster at `runtime/data/agents.json`. Bundled SDK and\n"
      + "dependency license texts are in `runtime/THIRD_PARTY_LICENSES.txt`.\n\n"
      + readText("THIRD_PARTY_NOTICES.md"));
    put("README.md", pluginReadme(target));
    put("BUNDLE.json", json({
      name: PLUGIN_ID,
      version: pkg.version,
      target,
      node: pkg.engines.node,
      generator: `esbuild@${esbuild.version}`,
      dependencies: dependencies.packages,
      files: Object.fromEntries([...files].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)
        .map(([name, content]) => [name, digest(content)])),
    }));
    for (const [name, content] of files) artifacts.set(`plugins/${target}/${name}`, content);
  }
  artifacts.set(".agents/plugins/marketplace.json", Buffer.from(json({
    name: MARKETPLACE_ID,
    interface: { displayName: "Fooljack Agency Agents" },
    plugins: [{
      name: PLUGIN_ID,
      source: { source: "local", path: "./plugins/codex" },
      policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
      category: "Productivity",
    }],
  })));
  artifacts.set(".claude-plugin/marketplace.json", Buffer.from(json({
    name: MARKETPLACE_ID,
    owner: { name: "Fooljack" },
    metadata: { description: "Offline specialist router plugins by Fooljack.", version: pkg.version },
    plugins: [{
      name: PLUGIN_ID,
      source: "./plugins/claude-code",
      description: metadata.description,
      version: pkg.version,
    }],
  })));
  return artifacts;
}

async function buildPlugins({ check = false } = {}) {
  const artifacts = await generateArtifacts();
  const mismatches = [];
  for (const [file, content] of artifacts) {
    const dest = path.join(ROOT, file);
    if (fs.existsSync(dest) && fs.readFileSync(dest).equals(content)) continue;
    if (check) mismatches.push(file);
    else {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, content);
    }
  }
  if (mismatches.length) throw new Error(`Plugin artifacts are missing or stale; run npm run build:plugins:\n${mismatches.join("\n")}`);
  return artifacts.size;
}

if (require.main === module) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    console.error("Usage: node scripts/build-plugins.js [--check]");
    process.exitCode = 1;
  } else {
    buildPlugins({ check: args.includes("--check") }).then((count) => {
      console.log(`${args.includes("--check") ? "Verified" : "Built"} ${count} plugin/catalog files for Codex and Claude Code.`);
    }).catch((error) => { console.error(error.message); process.exitCode = 1; });
  }
}

module.exports = { generateArtifacts, buildPlugins, TARGETS, PLUGIN_ID, MARKETPLACE_ID, digest };
